# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KSScreenCaptureDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'KSScreenCapture', :path => '../'
  pod 'ACEDrawingView', '~> 2.0.1'

  # Pods for KSScreenCaptureDemo

  target 'KSScreenCaptureDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
